name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123
          MONGO_INITDB_DATABASE: test_data
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          node-app/package-lock.json
          frontend/package-lock.json
    
    - name: Install API dependencies
      run: |
        cd node-app
        npm ci
    
    - name: Install Frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run API tests
      run: |
        cd node-app
        npm test
      env:
        MONGODB_URI: mongodb://admin:password123@localhost:27017/test_data?authSource=admin
        NODE_ENV: test
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Run Frontend tests
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        cd node-app && npm audit --audit-level moderate
        cd ../frontend && npm audit --audit-level moderate

  docker:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and test Docker images
      run: |
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml up -d
        sleep 30
        docker compose -f docker-compose.yml ps
        docker compose -f docker-compose.yml logs
        docker compose -f docker-compose.yml down
